### ISSUE TITLE
Collaboration with IPFS Companion?

### ISSUE THREAD

**Issue by olizilla** [cloudflare/ipfs-ext#1]
This project is great! @lidel, @alanshaw, myself and others are working on bringing IPFS to the browser with the https://github.com/ipfs-shipyard/ipfs-companion web-extension.

It'd be great to talk about working together on bringing ipfs-sec / dnssec validation and e2e integrity checking to the ipfs-companion. Companion is more focused on integrating a locally running IPFS daemon with your browser, but it would clearly benefit from allowing e2e integrity checking when running without a local node. [js-ipfs](https://github.com/ipfs/js-ipfs) already does that validation work, and this project shows that there would be value in exposing an api or publishing a module for just validation logic would be useful.

The general direction of travel for us is to move to [base32 encoded CIDs](https://github.com/ipfs/ipfs/issues/337) so they can be used in URL origins, to better isolate content served from shared gateways, but we'll still want human friendly aliases and http fallback, so the DNSSEC work is super valuable!

Come and join us in #ipfs-in-web-browsers on freenode irc, if you'd like to chat. A few of us will be at [Cloudflare's London office tomorrow](https://www.meetup.com/london-ipfs/events/255386386/), so if you happen to be in town, or there are folks at that office we should talk to, let us know.

**Comment by DerrickF86** [comment]
Thanks I appreciate the kind words, you guys are doing some amazing, do you
have telegram we could chat on also ? I am preparing my traveling details
to London tonight. Just in York at the moment. Much easy to chat via
telegram or something. Let me know 👍 look forwarding to chatting with you
tomorrow maybe I'll pop by you office early. As the founder and CEO I'm
more on the business,contacts and strategy side, I can keep up tho don't
worry haha, my devs can go toe to toe is this aspect they are amazing guys.
Please let me know would love to get together and chat I have forwarded
them your last email as well 👌

Thank You,

Derrick Foote
Founder/CEO
RTrade Technologies Ltd.
www.rtradetechnologies.com
+17788598644

**Comment by olizilla** [comment]
@DerrickF86 the message you're responding to is intended for the developers of Cloudflare's IPFS extension; this is the issue tracker for [cloudflare/ipfs-ext](https://github.com/cloudflare/ipfs-ext). 

Please delete your comment when you get a moment, as it's significantly derailing to have that discussion here. We can chat more generally at the meet-up.

**Comment by Bren2010** [comment]
Thanks for reaching out, I responded in the IRC room. I'll check that if it comes to mind, but you can reach me with lower latency on email: brendan at cloudflare dot com.
