### ISSUE TITLE
Issue resolving routes with cloudflare-ipfs.com

### ISSUE THREAD

**Issue by rstormsf** [cloudflare/ipfs-ext#8]
From: https://community.cloudflare.com/t/issue-resolving-routes-with-cloudflare-ipfs-com/239877

## Problem:
I deployed my static website to ipfs and I use [cloudflare-ipfs.com](cloudflare-ipfs.com) to link my domain to ipfs hash.
The issue is that for some unknown reason the [cloudflare-ipfs.com](cloudflare-ipfs.com) resolver doesn’t want to resolve
http://demo.dementev.tech/compliance. It returns 400 http error.

The interesting part is if I try to access http://demo.dementev.tech/legal, it will return 302 and will append / at the end and it will resolve to http://demo.dementev.tech/legal/
The fix that I found is if I replace my CNAME record from `cloudflare-ipfs.com` to `gateway.ipfs.io`,
the issue goes away, so I suspect there is something wrong with cloudflare-ipfs resolver, specifically
with the route `compliance`. I wonder why is it?

App 1:
Subdomain: demo.dementev.tech
Canonical name: cloudflare-ipfs.com

App 2:
Subdomain: work.dementev.tech
Canonical name: gateway.ipfs.io

available routes for test: http://demo.dementev.tech/compliance, http://demo.dementev.tech/legal

**Comment by thibmeu** [comment]
Hi @rstormsf,

`/compliance` was a special endpoint on Cloudflare IPFS gateway. We have updated the configuration so the issue does not manifest.
